POST http://localhost:3048/api/services
Content-Type: application/json

{
    "name":"ah, esta funcionando",
    "description":"Alguma descrição",
    "status":"Ativo",
    "comments": [
        {
            "usuario":"Dinah Martins",
            "description":"TESTE PUT"
        }
    ] 
}

###

GET http://localhost:3048/api/services

###

GET http://localhost:3048/api/services/64ec7f48cc75ca6f78585768

###

DELETE http://localhost:3048/api/services/64ec7f48cc75ca6f78585761

###

PUT http://localhost:3048/api/services/64ec7fa0cc75ca6f78585763
Content-Type: application/json

{
    "name":"TESTE ATUALIZAÇÃO",
    "description":"Alguma descrição",
    "status":"em encerramento"
}

### ORDEM

POST http://localhost:3048/api/ordem
Content-Type: application/json

{
    "solicitante": "dinah martins",
    "setor": "produção",
    "sala": "5",
    "forno": "245",
    "cabeceira": "A",
    "status": "Aguardando atendimento",
    "services": [
        {
            "name":"TESTE ATUALIZAÇÃO",
            "description":"Alguma descrição",
            "status":"em encerramento",
            "comments": [
                {
                    "usuario":"Dinah Martins",
                    "description":"TESTE PUT"
                }
            ]    
        }
    ],
    "comments": [
        {
            "usuario":"Dinah Martins",
            "description":"TESTE PUT"
        }
    ]    
}

###

GET http://34.207.114.122:3048/api/ordem?page=1&limit=5&filter=17


###

GET http://localhost:3048/api/ordem?page=1&limit=5&ordemId=17


###

GET http://localhost:3048/api/ordem/15

###

DELETE http://localhost:3048/api/ordem/650a7fe2dc4ef4dbffb2d119

###

PUT http://localhost:3048/api/ordem/64f5b5ea38fa3424886f5ab9
Content-Type: application/json

{
    "title": "Ordem de serviço",
    "solicitante": "dinah martins",
    "setor": "produção",
    "sala": "5",
    "forno": "245",
    "cabeceira": "A",
    "status": "Em andamento",
    "estadoatual": "manutenção",
    "services": [
        {
            "name":"TESTE ATUALIZAÇÃO 4848",
            "description":"Alguma descrição",
            "status":"em encerramento"
        }
    ]
}


### COMMENTS

POST http://localhost:3048/api/comments
Content-Type: application/json

{
    "usuario":"Dinah Martins",
    "description":"Alguma descrição"
}

###

GET http://localhost:3048/api/comments

###

GET http://localhost:3048/api/comments/64ece6b6fc21e92a9cdea725

###

DELETE http://localhost:3048/api/comments/64ece662fc21e92a9cdea71f

###

PUT http://localhost:3048/api/comments/64ece6b6fc21e92a9cdea725
Content-Type: application/json

{
    "usuario":"Dinah Martins",
    "description":"TESTE PUT"
}

### USERS

POST http://localhost:3048/api/users
Content-Type: application/json

{
    "name": "Dinah Martins",
    "matricula":"60771aDA",
    "setor":"fundição",
    "turno":"noturno",
    "funcao":"mecanico",
    "email":"dinah@hotmail.com",
    "senha":"noturno"
}

###

GET http://localhost:3048/api/users

###

GET http://localhost:3048/api/users/64f5b36949f8c371b87ab492

###

DELETE http://localhost:3048/api/users/6501674063cfca1f845af57c

###

PUT http://localhost:3048/api/users/64f5b36949f8c371b87ab492
Content-Type: application/json

{
    "name": "Dinah Martins",
    "matricula":"60771aDA",
    "setor":"fundição",
    "supervisor":"Giovana Vitoria teste minha linda",
    "turno":"noturno"
}