POST http://localhost:3048/api/services
Content-Type: application/json

{
    "name":"ah, esta funcionando",
    "description":"Alguma descrição",
    "status":"Ativo",
    "comments": [
        {
            "usuario":"Dinah Martins",
            "description":"TESTE PUT"
        }
    ] 
}

###

GET http://localhost:3048/api/services

###

GET http://localhost:3048/api/services/64ec7f48cc75ca6f78585768

###

DELETE http://localhost:3048/api/services/64ec7f48cc75ca6f78585761

###

PUT http://localhost:3048/api/services/64ec7fa0cc75ca6f78585763
Content-Type: application/json

{
    "name":"TESTE ATUALIZAÇÃO",
    "description":"Alguma descrição",
    "status":"em encerramento"
}

### ORDEM

POST http://localhost:3048/api/ordem
Content-Type: application/json

{
    "solicitante": "6569634528b16fb7838cafdb"
    ,
    "solicitante_name": "dinah",
    "setor_solicitante": "dinah",
    "setor": "655be5c6585d76b1ab1ca7e5",
    "equipe": "655bece8f2da4148eba30981",
    "sala": 4
    ,
    "forno": "245",
    "cabeceira": "A",
    "status": "Aguardando atendimento",
    "urgencia": "teste",
    "services": [
        {
            "name":"TESTE ATUALIZAÇÃO",
            "description":"Alguma descrição",
            "status":"em encerramento"

        }
    ],
    "comments": [
        {
            "usuario":"Dinah Martins",
            "description":"TESTE PUT"
        }
    ]    
}

###

GET http://localhost:3048/api/ordem?page=1&limit=5&filter=77

###

GET http://localhost:3048/api/ordem


###

GET http://localhost:3048/api/ordem?page=1&limit=5&ordemId=145


###

GET http://localhost:3048/api/ordem/655c0400f66b31437ec363b3

###

DELETE http://localhost:3048/api/ordem/65696746c470976a965159fd

###

PUT http://localhost:3048/api/ordem/64f5b5ea38fa3424886f5ab9
Content-Type: application/json

{
    "title": "Ordem de serviço",
    "solicitante": "dinah martins",
    "setor": "produção",
    "sala": "5",
    "forno": "245",
    "cabeceira": "A",
    "status": "Em andamento",
    "estadoatual": "manutenção",
    "services": [
        {
            "name":"TESTE ATUALIZAÇÃO 4848",
            "description":"Alguma descrição",
            "status":"em encerramento"
        }
    ]
}


### COMMENTS

POST http://localhost:3048/api/comments
Content-Type: application/json

{
    "usuario":"Dinah Martins",
    "description":"Alguma descrição"
}

###

GET http://localhost:3048/api/comments

###

GET http://localhost:3048/api/comments/64ece6b6fc21e92a9cdea725

###

DELETE http://localhost:3048/api/comments/64ece662fc21e92a9cdea71f

###

PUT http://localhost:3048/api/comments/64ece6b6fc21e92a9cdea725
Content-Type: application/json

{
    "usuario":"Dinah Martins",
    "description":"TESTE PUT"
}

### USERS


GET http://localhost:3048/api/usersPrivate/653c81c24ae88d9c03b2f40e

###

POST http://localhost:3048/api/auth/register
Content-Type: application/json

{
    "name": "dinah doria",
    "matricula":"1234",
    "setor":"655be3fd08346d6f62ae7a56",
    "turno":"manha",
    "equipe":"6569783744abf5a3198e2de0",
    "email":"dinahprod@gmail.com",
    "senha":"outrasenha",
    "situacao":"pendente",
    "roles": "655fa4283cd09a126e61f95e"
    
}

###

POST http://localhost:3048/api/auth/login
Content-Type: application/json

{

    "email":"dinah-dd2428@hotmail.com",
    "senha":"outrasenha"
}

###

GET http://localhost:3048/api/auth/register

###

GET http://localhost:3048/api/auth/register/6568e04f68e2728e8b3aaaa0

###

GET http://localhost:3048/api/auth/register/email?email=giovana@gmail.com

###

DELETE http://localhost:3048/api/auth/register/6557a8370aac2bc3ce21c607

###

PUT http://localhost:3048/api/auth/register/654435d92234e0e63f8182ba
Content-Type: application/json

{

    "name": "dinah doria",
    "matricula":"1234",
    "setor":"fundição",
    "turno":"manha",
    "funcao":"mecanico",
    "email":"dinah-dd2428@hotmail.com",
    "senha":"outrasenha",
    "situacao":"pendente",
    "roles": "admin"
    
}


### ROLES

POST http://localhost:3048/api/usersroles
Content-Type: application/json

{
    "name": "ROLE_MEC",
    "description": "Mecânica"
    
}

###

GET http://localhost:3048/api/usersroles

###

DELETE http://localhost:3048/api/usersroles/6545bbc2c05adf0df42e48cb

###

PUT http://localhost:3048/api/usersroles/654435d92234e0e63f8182ba
Content-Type: application/json

{

    "name": "dinah doria",
    "matricula":"1234",
    "setor":"fundição",
    "turno":"manha",
    "funcao":"mecanico",
    "email":"dinah-dd2428@hotmail.com",
    "senha":"outrasenha",
    "situacao":"pendente",
    "roles": "admin"
    
}

### 

POST http://localhost:3048/api/services
Content-Type: application/json

{
    "name":"ah, esta funcionando",
    "description":"Alguma descrição",
    "status":"Ativo",
    "comments": [
        {
            "usuario":"Dinah Martins",
            "description":"TESTE PUT"
        }
    ] 
}

###

#EQUIPE

GET http://localhost:3048/api/equipe

### 
POST http://localhost:3048/api/equipe
Content-Type: application/json

{  
    "equipeName":"PRODUCAO"
    
}

###

GET http://localhost:3048/api/equipe/655bdd1386440174fc3e149c

###

DELETE http://localhost:3048/api/equipe/655bdd1386440174fc3e149c

###

PUT http://localhost:3048/api/equipe/655be3ea08346d6f62ae7a53
Content-Type: application/json

{  
    "equipeName":"ELETRICA"
    
}


#SETOR
###

GET http://localhost:3048/api/setor

### 
POST http://localhost:3048/api/setor
Content-Type: application/json

{  
    "name":"MFS48",
    "equipe": [
        "655be3ea08346d6f62ae7a53"
    ]
}

###

GET http://localhost:3048/api/setor/655be5c6585d76b1ab1ca7e5

###

DELETE http://localhost:3048/api/setor/655bed3c6cee638bcd00fbcf

###

PUT http://localhost:3048/api/setor/655be5c6585d76b1ab1ca7e5
Content-Type: application/json

{  
    "name":"MSF"
}

#SALA
###

GET http://localhost:3048/api/sala

### 
POST http://localhost:3048/api/sala
Content-Type: application/json

{  
    "salaNumber":"4"
    
}

###

GET http://localhost:3048/api/sala/655be1a1de840472ecebfd0f

###

DELETE http://localhost:3048/api/sala/655be1a1de840472ecebfd0f

###

PUT http://localhost:3048/api/sala/655be40e08346d6f62ae7a5a
Content-Type: application/json

{  
    "salaNumber":"4"
}

#LOG
###

GET http://localhost:3048/api/log

### 
POST http://localhost:3048/api/log
Content-Type: application/json

{  
    "userId":"6569634528b16fb7838cafdb",
    "userName":"Dinah",
    "action":"create",
    "entity":"Ordem",
    "entityId":"6570909e48e50345c019588a",
    "details":"Criado ordem de serviço"
    
}

###

GET http://localhost:3048/api/log/entity/184


###

GET http://localhost:3048/api/log/entity/65715ec3d05eb6a79f92bf7f